apiVersion: v1
kind: Service
metadata:
  name: node-web-app-1-service
spec:
  type: NodePort
  selector:
    app: node-web-app-1
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 3000
      targetPort: 3000
      nodePort: 30111